Fix inaccurate seeking.
react-native-community/react-native-video pull request #2511
Opened 2021-10-15 09:54 UTC by hossein-zare

2022-04-26 21:33 UTC, freeboub reviewed
Same patch available here: https://github.com/react-native-video/react-native-video/pull/2545

2022-04-27 16:21 UTC, volpstar commented
@freeboub The linked patch was closed and not merged. Can you please re-review and merge if this PR looks good to you?

2022-04-27 16:35 UTC, hossein-zare commented
@freeboub @volpstar 
I tested this PR (months ago) on Android 9 it worked well but on Android 5 the app crashed.

2022-04-27 17:31 UTC, freeboub commented
@hossein-zare can you check if android api > 21 to enable the fix please ? @volpstar i don't have rights to merge PRs :)

2022-04-27 17:33 UTC, freeboub requested changes
Can you check api > 21 to use the second parameter, and remove commented line

2022-04-28 20:33 UTC, hossein-zare commented
@freeboub I'm sorry, I don't work with react-native anymore.

2022-05-01 18:22 UTC, hueniverse commented
We need two reviews approving this change to merge.

2022-05-25 09:26 UTC, SmartArray commented
tACK.

We need this feature upstream please.

2022-05-25 09:27 UTC, SmartArray requested changes
tACK

We need this feature upstream please.

2022-05-25 09:27 UTC, SmartArray commented on android/src/main/java/com/brentvatne/react/ReactVideoView.java
> +            // super.seekTo(msec);
Remove this comment

2022-06-21 11:26 UTC, armadilio3 commented
@hueniverse I think this can be closed. This change is meant for the media player that has been removed in 6.0

2022-06-22 02:46 UTC, SmartArray commented
@armadilio3 I am not quite sure, we are not using the media player but the seek function.
And the seek function works quite well on ios but not on android. I think this is still a bug that needs to be fixed?

2022-06-22 06:23 UTC, hueniverse commented
@freeboub Can you help sort this out?

2022-06-22 19:47 UTC, freeboub commented
I confirm this is old player, let's close this PR

2022-06-22 19:47 UTC, closed without merging